### ISSUE TITLE
도메인 Member에 대한 필드 정의 부탁드립니다.

### ISSUE THREAD

**Issue by Yong-ga-ri** [Rhythm-Finders/play-ground#1]
## 도메인 Member 정의

> 회원으로 게시글(Post)을 필터링해야하기에, Member에 대한 필드 정의가 필요합니다.

## Detail

- [ ] domain `Member` 정의

## References(Optional)
[2024-07-25 정기미팅](https://www.notion.so/ohgiraffers/play-ground-59d02702e7a4439aad91f88a965a63ce?pvs=4)

**Comment by JeongJunSeo99** [comment]
Member 필드값입니다

    private int id;
    private String nickname;
    private String email;
    private String pw;
    private String name;
    private int age;
    private Gender gender;
    private String[] myCategory;
    private Role role;
    private boolean flag;

**Comment by Yong-ga-ri** [comment]
감사합니다!

**Comment by Yong-ga-ri** [comment]
> Member 필드값입니다
> 
> ```
> private int id;
> private String nickname;
> private String email;
> private String pw;
> private String name;
> private int age;
> private Gender gender;
> private String[] myCategory;
> private Role role;
> private boolean flag;
> ```

@Bang1999 님 브랜치에서 정의된 필드와 상이한 부분이 있으니 확인 부탁드립니다!
