### ISSUE TITLE
Post File Input 처리

### ISSUE THREAD

**Issue by Bang1999** [Rhythm-Finders/play-ground#3]
## 기능 설명

> Post File Input 처리

## Detail

- [x] repository 파일의 registPost 메소드 주석 확인 부탁드립니다.
- [x] repository 파일의 deletePost 메소드 주석 확인 부탁드립니다.

## References(Optional)
![image](https://github.com/user-attachments/assets/fa5a570b-7611-43cf-94fe-b2f5328b3b6a)

**Comment by Yong-ga-ri** [comment]
완료했습니다.
